### PR TITLE
Handle empty files

### PR DESCRIPTION
**Pull request by ErinWeisbart**
Allows processing to handle situation where some objects were not detected in a site.

### CODE REVIEW

**Comment by gwaygenomics** [comment]
Looks like we're seeing some duplicate commits creep in. This is fine - we just need to make sure that when we're creating new branches, we are creating them from up-to-date synced masters

**Comment by ErinWeisbart** [comment]
This shouldn't have the Merge... commit b8a0ed4 but I can't figure out how to get rid of it...

**Comment by gwaygenomics** [comment]
short of deleting history (eek!) it cannot be removed. The branch was created from an older master and then not properly synced after the other was merged. Its nbd and breaks nothing.

In the future, making sure new branches are created from an up-to-date master (git fetch upstream; git merge upstream/master; **git push**) will prevent this. It happens all the time, especially when we're pushing.

LMK when ready for review

**Comment by ErinWeisbart** [comment]
Drats. Ready for review.

**Pull request merged**
